### ISSUE TITLE
EPUB/Mobiファイルの配布リンク切れ

### ISSUE THREAD

**Issue by knokmki612** [tdtds/esr_trilogy_ja#3]
https://tdtds.github.io/esr_trilogy_ja/ にて配布されているEPUB/Mobiファイルのリンク(6箇所)が有効でなくなっています。

例えば、 https://dl.dropboxusercontent.com/u/139551/cathedral.epub にアクセスすると、"ファイルが見つかりません"というメッセージが記載されたページが表示されます。

**Comment by knokmki612** [comment]
配布の再開等の予定はありますでしょうか？

**Comment by tdtds** [comment]
おー、そうですね、Dropboxが直リンクをできなくしたからか。ちょっと考えます。ここのReleasesに入れるのが良いかな。

**Comment by tdtds** [comment]
直ったと思います〜。確認したらcloseしちゃってください。

**Comment by knokmki612** [comment]
リンクが有効であることを確認しました！ありがとうございます！！
